name: Collect Env
description: Collect env values and write to a file
author: JeongMin Oh

branding:
  icon: file-plus
  color: purple

inputs:
  prefix:
    description: The prefix to collect
    required: false
  output:
    description: The file to write to
    required: true
  remove-prefix:
    description: The prefix to remove
    required: false
    type: boolean
    default: true

runs:
  using: node24
  main: ./dist/index.js
